// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXbph-cPy6JIAofn_IBKD1mL2q_6zkB1M',
    appId: '1:556329711074:web:d3e7543c3a0778e88bf5bb',
    messagingSenderId: '556329711074',
    projectId: 'user-registration-4-ea227',
    authDomain: 'user-registration-4-ea227.firebaseapp.com',
    storageBucket: 'user-registration-4-ea227.firebasestorage.app',
    measurementId: 'G-BV49PTM6KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxGzDivIaYAWed7mEJ1OtNsE_tFNVkcpE',
    appId: '1:556329711074:android:a16901626ba321488bf5bb',
    messagingSenderId: '556329711074',
    projectId: 'user-registration-4-ea227',
    storageBucket: 'user-registration-4-ea227.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7X47c5GIDpzo6nlHSlWJu5bAx2jbIWM',
    appId: '1:556329711074:ios:d0739254b94764be8bf5bb',
    messagingSenderId: '556329711074',
    projectId: 'user-registration-4-ea227',
    storageBucket: 'user-registration-4-ea227.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg7X47c5GIDpzo6nlHSlWJu5bAx2jbIWM',
    appId: '1:556329711074:ios:d0739254b94764be8bf5bb',
    messagingSenderId: '556329711074',
    projectId: 'user-registration-4-ea227',
    storageBucket: 'user-registration-4-ea227.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXbph-cPy6JIAofn_IBKD1mL2q_6zkB1M',
    appId: '1:556329711074:web:8fd3a4b3d387fdc48bf5bb',
    messagingSenderId: '556329711074',
    projectId: 'user-registration-4-ea227',
    authDomain: 'user-registration-4-ea227.firebaseapp.com',
    storageBucket: 'user-registration-4-ea227.firebasestorage.app',
    measurementId: 'G-53WN5HTGWF',
  );
}
