// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvC2s1OB___3Stc8waHub_-CBsgO8Q0Gg',
    appId: '1:838704839724:android:b1304df1dfa15956366589',
    messagingSenderId: '838704839724',
    projectId: 'user-registration-day2',
    storageBucket: 'user-registration-day2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPBoT2EekmNKX2oBDdJ_YElSn81fjN8sk',
    appId: '1:838704839724:web:4ea202eb926b273b366589',
    messagingSenderId: '838704839724',
    projectId: 'user-registration-day2',
    authDomain: 'user-registration-day2.firebaseapp.com',
    storageBucket: 'user-registration-day2.firebasestorage.app',
    measurementId: 'G-HTSB04LKQN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qA1vP4EwSDAqN1b41WNMfVyJUFQAiho',
    appId: '1:838704839724:ios:4969051c3436bc9d366589',
    messagingSenderId: '838704839724',
    projectId: 'user-registration-day2',
    storageBucket: 'user-registration-day2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qA1vP4EwSDAqN1b41WNMfVyJUFQAiho',
    appId: '1:838704839724:ios:4969051c3436bc9d366589',
    messagingSenderId: '838704839724',
    projectId: 'user-registration-day2',
    storageBucket: 'user-registration-day2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPBoT2EekmNKX2oBDdJ_YElSn81fjN8sk',
    appId: '1:838704839724:web:553ce95d01922396366589',
    messagingSenderId: '838704839724',
    projectId: 'user-registration-day2',
    authDomain: 'user-registration-day2.firebaseapp.com',
    storageBucket: 'user-registration-day2.firebasestorage.app',
    measurementId: 'G-9VQDP3SRSL',
  );

}